### ISSUE TITLE
No more packages for mr-mips target?

### ISSUE THREAD

**Issue by trenta3** [cuihaoleo/lede-mr-mips#4]
Thanks a lot for the great project.
I've successfully installed a 17.01.4 image in metarouter.
Unfortunately i can't download some of the `kmod-` packages.

In `/etc/opkg/distfeeds.conf`:
```
src/gz reboot_core http://downloads.lede-project.org/releases/17.01.4/targets/mr-mips/generic/packages
```
Unfortunately it seems that http://downloads.lede-project.org/releases/17.07.4/targets/mr-mips is non-existent.

Do you have any other sources where I can download them or should I rebuild all of them and host on my server?

**Comment by cuihaoleo** [comment]
mr-mips target is not officially supported by OpenWRT/LEDE. So you won't be able to download packages from downloads.lede-project.org.

You can use my repo:
```
src/gz reboot_core http://fs.i-yu.me/lede-mr-mips/v17.01.4_171226/packages/core
src/gz reboot_base http://fs.i-yu.me/lede-mr-mips/v17.01.4_171226/packages/base
```

If there is still no desired packages, then you have to build them yourself.

**Comment by cuihaoleo** [comment]
Emm, I upgrade my whole site to HTTPs, and may cause opkg connection problem if SSL-related packages are not installed.

I will add HTTP access for fs.i-yu.me domain tomorrow.

**Comment by trenta3** [comment]
Thank you very much.
I think I got mislead by the default feeds that gets installed with the image in your site fs.i-yu.me.
