### ISSUE TITLE
Imagens not acessible more 

### ISSUE THREAD

**Issue by ca4ti** [cuihaoleo/lede-mr-mips#6]
https://forum.mikrotik.com/viewtopic.php?t=128998

I upload the rootfs image, imagebuilder and SDK here:
https://fs.i-yu.me/lede-mr-mips/v17.01.4_171226/misc/

**Comment by cuihaoleo** [comment]
Should be back online now. I am migrating my site to a new domain.

But this image is quite old (and not really stable). Hopefully someone can continue it.
